lsi:            false
highlighter:    pygments
exclude:        ["script", "vendor", "Gemfile", "Gemfile.lock", "config.ru", "Procfile", "Rakefile", "readme.md", "scss"]
permalink:      /writing/:title
markdown:       kramdown
markdown_ext:   markdown,mkd,mkdn,md
name:           Dung Thai's Blog
description:    "The personal site of Dung Thai, computer scientist, math lover and a robot ;) This is my wonderland of code, not-so-brain-cracking things I have read and life *yes, I have one*. The views expressed are my own."
url:            http://dungtn.github.io
gems:
      - jekyll-redirect-from
