title: ML Revelation
description: Just another blog about Machine Learning
author: Dung (June) Thai
github: https://github.com/duungtn
about: UMass grad student.
disqus_shortname: https-dungtn-github-io
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "https://twitter.com/dgthai"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/dung-thai"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/dungtn"

share:
  twitter_username: dungtn

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://dungtn.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
